[project]
name = "dkblytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dkb-robo>=0.31.2",
    "polars>=1.32.2",
]
